WIDTH, HEIGHT = 1280, 760
TILE_SIZE = 10

FPS = 40
MAX_UPDATE_FREQ = 120
INITIAL_UPDATE_FREQ = MAX_UPDATE_FREQ

GEN_RANDOM_QUANTIFIER = 15

CONTEXT_PLANE_WIDTH = 130
GAME_WIDTH = WIDTH - CONTEXT_PLANE_WIDTH
GRID_WIDTH = GAME_WIDTH // TILE_SIZE
GRID_HEIGHT = HEIGHT // TILE_SIZE
